---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: configmap-container
      image: httpd
      envFrom:
        # Load the Complete ConfigMap
        - configMapRef:
            name: test-configmap


---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: configmap-container
      image: httpd
      env:
        - name: CAR
          valueFrom:
            configMapKeyRef:
              name: test-configmap
              key: car
        - name: COUNTRY
          valueFrom:
            configMapKeyRef:
              name: test-configmap
              key: country
